# DEPRICATED see new location EXT:hh_simple_job_posts/sites/config.yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      job.json: 587951
  JobPluginDetail:
    type: Extbase
    extension: HhSimpleJobPosts
    plugin: jobsdetail
    defaultController: 'Jobpost::switch'
    routes:
      - routePath: '/{job_slug}'
        _controller: 'Jobpost::switch'
        _arguments:
          job_slug: jobpost
    aspects:
      job_slug:
        type: PersistedAliasMapper
        tableName: tx_hhsimplejobposts_domain_model_jobpost
        routeFieldName: slug
  JobPluginList:
    type: Extbase
    extension: HhSimpleJobPosts
    plugin: jobslist
    defaultController: 'Jobpost::list'
    routes:
      - routePath: '/detail/{job_slug}'
        _controller: 'Jobpost::switch'
        _arguments:
          job_slug: jobpost
    aspects:
      job_slug:
        type: PersistedAliasMapper
        tableName: tx_hhsimplejobposts_domain_model_jobpost
        routeFieldName: slug
