<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_simple_job_posts"
 *
 * Auto generated by Extension Builder 2021-02-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_simple_job_posts'] = [
    'title' => 'Job posts - simple',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christian Hackl',
    'author_email' => 'chackl@hauer-heinrich.de',
    'state' => 'beta',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'tt_address' => ''
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
