routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      job.json: 587951

  JobPluginList:
    type: Extbase
    extension: HhSimpleJobPosts
    plugin: Jobslist
    defaultController: 'Jobpost::list'
    routes:
      - routePath: '/{job_slug}'
        _controller: 'Jobpost::switch'
        _arguments:
          job_slug: jobpost
    aspects:
      job_slug:
        type: PersistedAliasMapper
        tableName: tx_hhsimplejobposts_domain_model_jobpost
        routeFieldName: slug

  JobPluginDetail:
    type: Extbase
    extension: HhSimpleJobPosts
    plugin: Jobsdetail
    defaultController: 'Jobpost::show'
    routes:
      - routePath: '/{job_slug}'
        _controller: 'Jobpost::switch'
        _arguments:
          job_slug: jobpost
    aspects:
      job_slug:
        type: PersistedAliasMapper
        tableName: tx_hhsimplejobposts_domain_model_jobpost
        routeFieldName: slug
